[package]
name = "yugo"
version = "1.0.0"
upgrade_policy = "compatible"
edition = "2024.beta"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "main" }

[addresses]
yugo = "_"

[dev-addresses]
yugo = "0x123"
user = "0x456"
